# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sagekbeard.com"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Sage K. Beard
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "Portfolio and resume for Sage K. Beard" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Designer, Developer, Writer, and Dad.</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: sagek711@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble: 
  flickr:
  github: "sagebeard"
  google_plus:
  instagram: "sagekbeard"
  linkedin: https://www.linkedin.com/in/sagekbeard # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "sagekbeard"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-86917852-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]